name = "isochronemaptoolwalk"
main = "isochroneMapTool-main/cloudflare/worker.js"
compatibility_date = "2026-06-09"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./isochroneMapTool-main/dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]
